export type TargetLocation = {
  location_id: number;
  name: string;
  location_type: string;
  region_name: string;
  system_name: string;
};

export type SourceSummary = {
  source_location_id: number;
  source_market_name: string;
  source_security_status: number;
  purchase_units_total: number;
  source_units_available_total: number;
  target_demand_day_total: number;
  target_supply_units_total: number;
  target_dos_weighted: number;
  in_transit_units: number;
  assets_units: number;
  active_sell_orders_units: number;
  source_avg_price_weighted: number;
  target_now_price_weighted: number;
  target_period_avg_price_weighted: number;
  risk_pct_weighted: number;
  warning_count: number;
  target_now_profit_weighted: number;
  target_period_profit_weighted: number;
  capital_required_total: number;
  roi_now_weighted: number;
  roi_period_weighted: number;
  total_item_volume_m3: number;
  shipping_cost_total: number;
  demand_source_summary: string;
  confidence_score_summary: number;
};

export type OpportunityItem = {
  type_id: number;
  item_name: string;
  source_security_status: number;
  purchase_units: number;
  source_units_available: number;
  target_demand_day: number;
  target_supply_units: number;
  target_dos: number;
  in_transit_units_item: number;
  assets_units_item: number;
  active_sell_orders_units_item: number;
  source_station_sell_price: number;
  target_station_sell_price: number;
  target_period_avg_price: number;
  risk_pct: number;
  warning_flag: boolean;
  target_now_profit: number;
  target_period_profit: number;
  capital_required: number;
  roi_now: number;
  roi_period: number;
  item_volume_m3: number;
  shipping_cost: number;
  demand_source: string;
  confidence_score: number;
};
